### PR TITLE
arch Aur support

### PR DESCRIPTION
**Pull request by Ns2Kracy**

### CODE REVIEW

**Review by tigerinus — CHANGES_REQUESTED** [review]
PKGBUILD should be generated instead of hard coded, to reduce maintenance cost for future.

**Comment by JesseKoldewijn** [comment]
Maybe throw the generation of the PKGBUILD inside of a github action?

**Comment by Ns2Kracy** [comment]
> Maybe throw the generation of the PKGBUILD inside of a github action?

I'm learning to write a script to generate all the PKGBUILD files and use the github action to push them to Archlinux Aur.But my level is relatively low, and I have not been able to satisfy myself with what I write.

**Comment by JesseKoldewijn** [comment]
> > Maybe throw the generation of the PKGBUILD inside of a github action?
> 
> I'm learning to write a script to generate all the PKGBUILD files and use the github action to push them to Archlinux Aur.But my level is relatively low, and I have not been able to satisfy myself with what I write.

Fair fair, I do think that implementing the PKGBUILD creation/update from github actions would be the most ideal workflow tho.. I dont have all that much experience with writing PKGBUILD files alone already let alone writing them from github actions. So I'm in kind of the same boat as you.

**Pull request closed without merging**
